ALTER TABLE "LobbyPresence"
  ADD COLUMN "yaw"       DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "vx"        DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "vz"        DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "isRunning" BOOLEAN          NOT NULL DEFAULT FALSE,
  ADD COLUMN "isJumping" BOOLEAN          NOT NULL DEFAULT FALSE;
