import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

interface RawScene {
  nodes: Record<string, { id: string; label: string; parent: { id: string }; type: string }>
  entityConstructorProps: Record<string, { source?: string }>
  entityProps: Record<string, {
    position?: [number, number, number]
    rotation?: [number, number, number]
    scale?: [number, number, number]
  }>
}

const ASSETS = [
  'Blue_House',
  'Green_House',
  'Yellow_House',
  'Red_House',
  'Main_House',
  'Bush_Classik',
  'Tree_Bigger',
  'Tree_Classic',
  'Grass',
  'Fence',
  'Tikvi',
  'Yagodi',
  'Ploshadka',
] as const

type Asset = (typeof ASSETS)[number]

const SOURCE_PATH = resolve('SCENA/Scene.zcomp')
const OUT_PATH = resolve('src/components/world/mattercraft-scene-data.ts')

const data = JSON.parse(readFileSync(SOURCE_PATH, 'utf8')) as RawScene

interface Instance {
  asset: Asset
  position: [number, number, number]
  rotation: [number, number, number]
  scale: [number, number, number]
  label: string
}

const instances: Instance[] = []

for (const [id, node] of Object.entries(data.nodes)) {
  if (node.type !== '@zcomponent/three/lib/components/models/GLTF#GLTF') continue
  const ctor = data.entityConstructorProps[id]
  if (!ctor?.source) continue
  const match = ctor.source.match(/\.\/([^/]+)\.glb$/)
  if (!match) continue
  const baseName = match[1]
  if (!ASSETS.includes(baseName as Asset)) {
    console.warn(`unknown asset ${baseName} (id ${id})`)
    continue
  }
  const props = data.entityProps[id] ?? {}
  instances.push({
    asset: baseName as Asset,
    position: props.position ?? [0, 0, 0],
    rotation: props.rotation ?? [0, 0, 0],
    scale: props.scale ?? [1, 1, 1],
    label: node.label,
  })
}

instances.sort((a, b) => a.label.localeCompare(b.label))

const fmtTuple = (t: [number, number, number]): string =>
  `[${t.map((n) => Number(n.toFixed(6))).join(', ')}]`

const lines: string[] = []
lines.push('// AUTO-GENERATED by scripts/extract-scene.ts — do not edit by hand.')
lines.push('// Source: SCENA/Scene.zcomp')
lines.push('')
lines.push("export const SCENE_ASSETS = [")
for (const a of ASSETS) lines.push(`  '${a}',`)
lines.push('] as const')
lines.push('')
lines.push('export type SceneAsset = (typeof SCENE_ASSETS)[number]')
lines.push('')
lines.push('export interface SceneInstance {')
lines.push('  asset: SceneAsset')
lines.push('  position: [number, number, number]')
lines.push('  rotation: [number, number, number]')
lines.push('  scale: [number, number, number]')
lines.push('  label: string')
lines.push('}')
lines.push('')
lines.push('export const ASSET_URLS: Record<SceneAsset, string> = {')
for (const a of ASSETS) lines.push(`  ${a}: '/scena/${a}.glb',`)
lines.push('}')
lines.push('')
lines.push('export const SCENE_INSTANCES: readonly SceneInstance[] = [')
for (const inst of instances) {
  lines.push('  {')
  lines.push(`    asset: '${inst.asset}',`)
  lines.push(`    position: ${fmtTuple(inst.position)},`)
  lines.push(`    rotation: ${fmtTuple(inst.rotation)},`)
  lines.push(`    scale: ${fmtTuple(inst.scale)},`)
  lines.push(`    label: ${JSON.stringify(inst.label)},`)
  lines.push('  },')
}
lines.push('] as const')
lines.push('')
lines.push('export const GROUND_IMAGE = {')
lines.push("  src: '/scena/map.png',")
lines.push('  position: [0, 0, 0] as [number, number, number],')
lines.push('  rotation: [-Math.PI / 2, 0, 0] as [number, number, number],')
lines.push('  scale: [50, 50, 1] as [number, number, number],')
lines.push('} as const')
lines.push('')

writeFileSync(OUT_PATH, lines.join('\n'), 'utf8')

console.log(`extracted ${instances.length} instances → ${OUT_PATH}`)

const counts = new Map<Asset, number>()
for (const i of instances) counts.set(i.asset, (counts.get(i.asset) ?? 0) + 1)
for (const [a, c] of counts) console.log(`  ${a}: ${c}`)
