// AUTO-GENERATED by scripts/extract-lobby-scene.ts — do not edit by hand.
// Source: for-lobby/Scene.zcomp

export const LOBBY_SCENE_ASSETS = [
  'Bush_Classik',
  'Door',
  'Grass',
  'Tree_Bigger',
] as const

export type LobbySceneAsset = (typeof LOBBY_SCENE_ASSETS)[number]

export interface LobbySceneInstance {
  asset: LobbySceneAsset
  position: [number, number, number]
  rotation: [number, number, number]
  scale: [number, number, number]
  label: string
}

export const LOBBY_ASSET_URLS: Record<LobbySceneAsset, string> = {
  Bush_Classik: '/scena/Bush_Classik.glb',
  Door: '/scena/Door.glb',
  Grass: '/scena/Grass.glb',
  Tree_Bigger: '/scena/Tree_Bigger.glb',
}

export const LOBBY_SCENE_INSTANCES: readonly LobbySceneInstance[] = [
  {
    asset: 'Bush_Classik',
    position: [-14.8638, 1.165344, 21.993079],
    rotation: [0, 5.8304, 0],
    scale: [2, 2, 2],
    label: "Bush_Classik.glb",
  },
  {
    asset: 'Bush_Classik',
    position: [18.726533, 1.165344, 12.992379],
    rotation: [0, 0, 0],
    scale: [2, 2, 2],
    label: "Bush_Classik.glb 2",
  },
  {
    asset: 'Bush_Classik',
    position: [21.799458, 1.165344, -7.982374],
    rotation: [0, 1.167748, 0],
    scale: [2, 2, 2],
    label: "Bush_Classik.glb 3",
  },
  {
    asset: 'Bush_Classik',
    position: [-11.145045, 1.165344, -20.60767],
    rotation: [0, 3.214743, 0],
    scale: [2, 2, 2],
    label: "Bush_Classik.glb 4",
  },
  {
    asset: 'Bush_Classik',
    position: [-18.98432, 1.165344, -11.279951],
    rotation: [0, 3.214743, 0],
    scale: [2, 2, 2],
    label: "Bush_Classik.glb 5",
  },
  {
    asset: 'Bush_Classik',
    position: [-6.033298, 1.165344, 13.686199],
    rotation: [0, 3.214743, 0],
    scale: [2, 2, 2],
    label: "Bush_Classik.glb 6",
  },
  {
    asset: 'Door',
    position: [-20.265891, 1.992669, 20.898137],
    rotation: [0, 2.266772, 0],
    scale: [3, 2, 3],
    label: "Door.glb",
  },
  {
    asset: 'Door',
    position: [-20.782951, 1.992669, -20.92034],
    rotation: [0, 0.871668, 0],
    scale: [3, 2, 3],
    label: "Door.glb 2",
  },
  {
    asset: 'Door',
    position: [19.625203, 1.992669, 19.778188],
    rotation: [0, 0.871668, 0],
    scale: [3, 2, 3],
    label: "Door.glb 3",
  },
  {
    asset: 'Door',
    position: [21.257487, 1.992669, -20.672634],
    rotation: [0, 2.266772, 0],
    scale: [3, 2, 3],
    label: "Door.glb 4",
  },
  {
    asset: 'Grass',
    position: [-12.87752, 0, -6.533194],
    rotation: [0, -0.39086, 0],
    scale: [1, 1, 1],
    label: "Grass.glb",
  },
  {
    asset: 'Grass',
    position: [18.113507, 0, -5.550287],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 10",
  },
  {
    asset: 'Grass',
    position: [22.354071, 0, -13.593501],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 11",
  },
  {
    asset: 'Grass',
    position: [11.647779, 0, -23.21959],
    rotation: [0, -2.204478, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 12",
  },
  {
    asset: 'Grass',
    position: [4.587485, 0, -23.383749],
    rotation: [0, 1.420615, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 13",
  },
  {
    asset: 'Grass',
    position: [22.439254, 0, 5.259927],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 14",
  },
  {
    asset: 'Grass',
    position: [13.308341, 0, 22.203621],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 15",
  },
  {
    asset: 'Grass',
    position: [4.657035, 0, 22.442993],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 16",
  },
  {
    asset: 'Grass',
    position: [-14.319412, 0, 3.625323],
    rotation: [0, 0.909325, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 17",
  },
  {
    asset: 'Grass',
    position: [-6.991557, 0, 19.371767],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 2",
  },
  {
    asset: 'Grass',
    position: [-20.300762, 0, 5.626342],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 3",
  },
  {
    asset: 'Grass',
    position: [-13.377952, 0, 12.17561],
    rotation: [0, 0.909325, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 4",
  },
  {
    asset: 'Grass',
    position: [-22.006177, 0, -7.289018],
    rotation: [0, 1.686477, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 5",
  },
  {
    asset: 'Grass',
    position: [-22.837973, 0, -16.886636],
    rotation: [0, 0.799751, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 6",
  },
  {
    asset: 'Grass',
    position: [14.632643, 0, 5.757362],
    rotation: [0, 1.286833, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 7",
  },
  {
    asset: 'Grass',
    position: [-6.155194, 0, -14.936439],
    rotation: [0, -1.117352, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 8",
  },
  {
    asset: 'Grass',
    position: [14.296863, 0, -5.162601],
    rotation: [0, -0.657422, 0],
    scale: [1, 1, 1],
    label: "Grass.glb 9",
  },
  {
    asset: 'Tree_Bigger',
    position: [12.174053, 4.912538, -8.677293],
    rotation: [0, -1.358773, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb",
  },
  {
    asset: 'Tree_Bigger',
    position: [-20.863594, 4.912538, 12.296989],
    rotation: [0, 0, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 2",
  },
  {
    asset: 'Tree_Bigger',
    position: [-4.778295, 4.912538, 21.282472],
    rotation: [0, 2.199416, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 3",
  },
  {
    asset: 'Tree_Bigger',
    position: [-5.554925, 4.912538, -21.938237],
    rotation: [0, 4.430189, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 4",
  },
  {
    asset: 'Tree_Bigger',
    position: [-18.127641, 4.912538, -5.45586],
    rotation: [0, -0.583488, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 5",
  },
  {
    asset: 'Tree_Bigger',
    position: [8.412144, 4.912538, -20.901451],
    rotation: [0, -3.163284, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 6",
  },
  {
    asset: 'Tree_Bigger',
    position: [18.570008, 4.912538, 5.157857],
    rotation: [0, -0.04101, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 7",
  },
  {
    asset: 'Tree_Bigger',
    position: [5.486226, 4.912538, 13.539911],
    rotation: [0, 3.480831, 0],
    scale: [5, 5, 5],
    label: "Tree_Bigger.glb 8",
  },
] as const

export const LOBBY_GROUND_IMAGE = {
  src: '/scena/lobbymap.png',
  position: [0, 0, 0] as [number, number, number],
  rotation: [-Math.PI / 2, 0, 0] as [number, number, number],
  scale: [60, 60, 1] as [number, number, number],
} as const
